import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/src/context/AuthContext";
import { roboto } from "@/src/lib/fonts";



export const metadata: Metadata = {
  title: "Cotizador Nec",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} min-h-screen bg-gray/10 text-gray `}
      >

        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
