import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Cotizador Nec",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" min-h-screen bg-gradient-to-br from-indigo/30 to-purple text-gray"
      >
        {children}
      </body>
    </html>
  );
}
